# See
# - https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# - https://docs.github.com/en/actions/learn-github-actions/contexts
# - https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
name: docker build

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/docker-build.yml
      - "*.dockerfile"
      - files/*
  release:
    types:
      - published

jobs:
  build_nginx:
    name: Build nginx variant
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: baikal

    steps:
      - uses: actions/checkout@v3

      # See https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # See https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # See https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build nginx images
      - name: Build and push experimental image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v4
        with:
          file: nginx.dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
